### ISSUE TITLE
logging not working

### ISSUE THREAD

**Issue by iurimatias** [ethereum/pyethereum#200]
username@username-VirtualBox:~/pyethereum$ pyeth -L debug

```
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/username/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
INFO:app	starting	version='0.7.49-51-g36eb7ae'
Traceback (most recent call last):
  File "/usr/local/bin/pyeth", line 9, in <module>
    load_entry_point('pyethereum==0.7.49-51-g36eb7ae', 'console_scripts', 'pyeth')()
  File "/usr/local/lib/python2.7/dist-packages/pyethereum-0.7.49_51_g36eb7ae-py2.7.egg/pyethereum/eth.py", line 137, in main
    log_json=bool(config.getint('misc', 'log_json')))
  File "/usr/local/lib/python2.7/dist-packages/pyethereum-0.7.49_51_g36eb7ae-py2.7.egg/pyethereum/slogging.py", line 189, in configure
    configure_loglevels(config_string)
  File "/usr/local/lib/python2.7/dist-packages/pyethereum-0.7.49_51_g36eb7ae-py2.7.egg/pyethereum/slogging.py", line 143, in configure_loglevels
    assert ':' in config_string
AssertionError
```

**Comment by heikoheiko** [comment]
try:
`username@username-VirtualBox:~/pyethereum$ pyeth -L :DEBUG`
see `pyeth -h` for logging options.
