### ISSUE TITLE
test.vm.py compilation error

### ISSUE THREAD

**Issue by sveneh** [ethereum/pyethereum#201]
running python ./tests/test_vm.py

gives

```
Traceback (most recent call last):
  File "./python", line 44, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "../tests/test_vm.py", line 3, in <module>
    import pyethereum.processblock as pb
  File "/pyethereum/pyethereum/__init__.py", line 2, in <module>
    import utils
  File "/pyethereum/pyethereum/utils.py", line 7, in <module>
    import db
  File "/pyethereum/pyethereum/db.py", line 5, in <module>
    from pyethereum.slogging import get_logger
  File "/pyethereum/pyethereum/slogging.py", line 71, in <module>
    structlog.stdlib._nameToLevel['trace'] = TRACE
AttributeError: 'module' object has no attribute '_nameToLevel'
```

API change at structlog?

**Comment by heikoheiko** [comment]
fixed in 1dc44fe0e0ef8afc92dbd24eb4aa49cdd4a86f68
