### ISSUE TITLE
test_vm.py not working

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/pyethereum#204]
I got the following output when trying to execute a single vm test:
python ./tests/test_vm.py 201502031049PYTHON.json 
Traceback (most recent call last):
  File "./tests/test_vm.py", line 3, in <module>
    import pyethereum.processblock as pb
  File "/home/christoph/software/Ethereum/pyethereum/pyethereum/__init__.py", line 1, in <module>
    import utils
  File "/home/christoph/software/Ethereum/pyethereum/pyethereum/utils.py", line 7, in <module>
    import db
  File "/home/christoph/software/Ethereum/pyethereum/pyethereum/db.py", line 5, in <module>
    from pyethereum.slogging import get_logger
  File "/home/christoph/software/Ethereum/pyethereum/pyethereum/slogging.py", line 76, in <module>
    structlog.stdlib._NAME_TO_LEVEL['trace'] = TRACE
AttributeError: 'module' object has no attribute '_NAME_TO_LEVEL'

**Comment by CJentzsch** [comment]
pip install --upgrade structlog fixed it
