### ISSUE TITLE
Exception in thread on OS X Yosemite

### ISSUE THREAD

**Issue by tarassh** [ethereum/pyethereum#209]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/stoppable.py", line 31, in run
    self.loop_body()
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/chainmanager.py", line 198, in loop_body
    self.mine()
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/chainmanager.py", line 230, in mine
    if not self.add_block(block, forward=True):
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/chainmanager.py", line 301, in add_block
    if not block.validate_uncles():
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/blocks.py", line 257, in validate_uncles
    ancestor_chain = self.get_ancestor_list(MAX_UNCLE_DEPTH + 1)
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/blocks.py", line 244, in get_ancestor_list
    p = self.ancestors[-1] \
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/blocks.py", line 758, in get_parent
    raise UnknownParentException('Genesis block has no parent')
UnknownParentException: Genesis block has no parent

**Comment by heikoheiko** [comment]
looks like your database does not match the current version. please try to delete:
`/Library/Application\ Support/Pyethereum/`

**Comment by heikoheiko** [comment]
please run with `-L :DEBUG` when reporting errors.

**Comment by tarassh** [comment]
I have deleted statedb, but still same exception occurs:

Logs with DEBUG

/usr/bin/python /usr/local/bin/pyeth -L :DEBUG
INFO:app	starting	version='0.7.51-py2.7.egg'
DEBUG:app	config ready	
DEBUG:app	network	remote_host='207.12.89.180'
DEBUG:app	network	remote_port='30300'
DEBUG:app	network	listen_host='0.0.0.0'
DEBUG:app	network	listen_port='30303'
DEBUG:app	network	num_peers='10'
DEBUG:app	network	node_id='90bbf0927ce428182d815e4714a3519cc7c6a06bb9147136f96f3170dfe8b77190bbf0927ce428182d815e4714a3519cc7c6a06bb9147136f96f3170dfe8b771'
DEBUG:app	network	client_version='Ethereum(py)/darwin/0.8'
DEBUG:app	api	listen_host='0.0.0.0'
DEBUG:app	api	listen_port='30203'
DEBUG:app	api	api_path='/api/v02a'
DEBUG:app	misc	data_dir='/Users/tarasshchybovyk/Library/Application Support/Pyethereum'
DEBUG:app	misc	mining='30'
DEBUG:app	misc	logging=':DEBUG'
DEBUG:app	misc	log_json='0'
DEBUG:app	wallet	coinbase='6c386a4b26f73c802f34673f7248bb118f97424a'
INFO:eth.chain	opening chain	db_path='/Users/tarasshchybovyk/Library/Application Support/Pyethereum/statedb'
DEBUG:eth.chain	chain @	head_hash=<Block(#0 779b1b62)>
DEBUG:db	commit	db=<DB at 4516786504 uncommitted=3>
DEBUG:eth.chain	got genesis	genesis_hash=<Block(#0 779b1b62)>
DEBUG:eth.miner	mining	block_difficulty=130944L block_hash='bb9cc850adaf10979f7dff3c10be23c87349771f342dc2d61a6cc32c2cc20c9e' block_number=1L
DEBUG:net	Thread start to run	name=<PeerManager(Thread-1, started 4526612480)>
DEBUG:net	not enough peers	candidates=0 num_connected=0 required=10
DEBUG:net	reqesting new peers	candidates=0
INFO:net	TCP server started	ip='0.0.0.0' port=30303
DEBUG:net	Thread start to run	name=<ChainManager(Thread-2, started 4530819072)>
DEBUG:net	Setting UPNP	
Bottle v0.12.8 server starting up (using WaitressServer())...
Listening on http://0.0.0.0:30203/
Hit Ctrl-C to quit.

DEBUG:net	attempting connect	host='207.12.89.180' port=30300
serving on http://0.0.0.0:30203
DEBUG:net	connecting failed	error=timeout('timed out',) host='207.12.89.180' port=30300
DEBUG:net	not enough peers	candidates=0 num_connected=0 required=10
DEBUG:net	reqesting new peers	candidates=0
DEBUG:net	not enough peers	candidates=0 num_connected=0 required=10
DEBUG:net	reqesting new peers	candidates=0
DEBUG:net	UPNP device(s) detected	num=1
DEBUG:net	not enough peers	candidates=0 num_connected=0 required=10
DEBUG:net	reqesting new peers	candidates=0
DEBUG:eth.miner	nonce found	block_hash='b94d23570e1ad408e2f75da60b4a64b768fc44d54cef6606d3cd98b7ad2dac6b' block_nonce=131646
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/stoppable.py", line 31, in run
    self.loop_body()
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/chainmanager.py", line 198, in loop_body
    self.mine()
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/chainmanager.py", line 230, in mine
    if not self.add_block(block, forward=True):
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/chainmanager.py", line 301, in add_block
    if not block.validate_uncles():
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/blocks.py", line 257, in validate_uncles
    ancestor_chain = self.get_ancestor_list(MAX_UNCLE_DEPTH + 1)
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/blocks.py", line 244, in get_ancestor_list
    p = self.ancestors[-1] \
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51-py2.7.egg/pyethereum/blocks.py", line 758, in get_parent
    raise UnknownParentException('Genesis block has no parent')
UnknownParentException: Genesis block has no parent

**Comment by heikoheiko** [comment]
thx. please try to use the latest version from github development branch.

**Comment by tarassh** [comment]
Developer branch ok.
