### ISSUE TITLE
python setup.py install fails on OSX & Linux

### ISSUE THREAD

**Issue by nealrauhauser** [ethereum/pyethereum#214]
This is OSX 10.9.5 & python 2.7.5 failure

cc  -o upnpc-static upnpc.o libminiupnpc.a
ld: warning: ignoring file libminiupnpc.a, file was built for archive which is not the architecture being linked (i386): libminiupnpc.a
zip_safe flag not set; analyzing archive contents...
No eggs found in /tmp/easy_install-7K357E/miniupnpc-1.9/egg-dist-tmp-voMPw_ (setup script problem?)
error: Could not find required distribution miniupnpc

I tried brew install miniupnpc, which worked, removed the miniupnpc requirement from setup.py, and then the install runs to completion, but produces many errors while compiling. The resulting pyeth crashes as follows:

Traceback (most recent call last):
  File "/usr/local/bin/pyeth", line 8, in <module>
    load_entry_point('pyethereum==0.7.51-1-gd442c11-dirty', 'console_scripts', 'pyeth')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 318, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2221, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51_1_gd442c11_dirty-py2.7.egg/pyethereum/__init__.py", line 2, in <module>
    import utils
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51_1_gd442c11_dirty-py2.7.egg/pyethereum/utils.py", line 7, in <module>
    import db
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51_1_gd442c11_dirty-py2.7.egg/pyethereum/db.py", line 5, in <module>
    from pyethereum.slogging import get_logger
  File "/Library/Python/2.7/site-packages/pyethereum-0.7.51_1_gd442c11_dirty-py2.7.egg/pyethereum/slogging.py", line 71, in <module>
    structlog.stdlib._nameToLevel['trace'] = TRACE
AttributeError: 'module' object has no attribute '_nameToLevel'

This is Ubuntu on amd64 with python 2.7.5 after making similar effort to circumvent troubles with miniupnpc.

Processing pysha3-0.3.zip
Writing /tmp/easy_install-Vv5ERU/pysha3-0.3/setup.cfg
Running pysha3-0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Vv5ERU/pysha3-0.3/egg-dist-tmp-54ewfF
Modules/_sha3/sha3module.c:18:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

So ... no joy for Python users who want to experiment with Ethereum :-(

**Comment by konradkonrad** [comment]
Regarding your ubuntu problems:
```
#include "Python.h"
^
```
 -> seems you're missing the python-headers. Try installing the ubuntu package `python-dev`.

**Comment by konradkonrad** [comment]
@nealrauhauser I assume this is resolved. Feel free to reopen if not.
