### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by vibhor1403** [ethereum/pyethereum#234]
After installation, I ran the command "pyeth" and got the following error. Please suggest.

/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/vibhor/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
INFO:app	starting	version='0.8.52_113_ga6f6299-py2.7.egg'
INFO:eth.chainmgr	opening chain	db_path='/home/vibhor/.pyethereum/statedb'
Traceback (most recent call last):
  File "/usr/local/bin/pyeth", line 9, in <module>
    load_entry_point('pyethereum==0.8.52-113-ga6f6299', 'console_scripts', 'pyeth')()
  File "/usr/local/lib/python2.7/dist-packages/pyethereum-0.8.52_113_ga6f6299-py2.7.egg/pyethereum/eth.py", line 145, in main
    config_ready.send(sender=None, config=config)
  File "/usr/local/lib/python2.7/dist-packages/pyethereum-0.8.52_113_ga6f6299-py2.7.egg/pyethereum/dispatch/dispatcher.py", line 197, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/dist-packages/pyethereum-0.8.52_113_ga6f6299-py2.7.egg/pyethereum/chainmanager.py", line 222, in config_chainmanager
    chain_manager.configure(config)
  File "/usr/local/lib/python2.7/dist-packages/pyethereum-0.8.52_113_ga6f6299-py2.7.egg/pyethereum/chainmanager.py", line 49, in configure
    self.chain = Chain(db, genesis, new_head_cb=self._on_new_head)
  File "/usr/local/lib/python2.7/dist-packages/pyethereum-0.8.52_113_ga6f6299-py2.7.egg/pyethereum/chain.py", line 100, in __init__
    log.debug('chain @', head_hash=self.head)
  File "/usr/local/lib/python2.7/dist-packages/pyethereum-0.8.52_113_ga6f6299-py2.7.egg/pyethereum/chain.py", line 120, in head
    return blocks.get_block(self.blockchain, ptr)
  File "/usr/local/lib/python2.7/dist-packages/repoze.lru-0.6-py2.7.egg/repoze/lru/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/usr/local/lib/python2.7/dist-packages/pyethereum-0.8.52_113_ga6f6299-py2.7.egg/pyethereum/blocks.py", line 1300, in get_block
    blk = rlp.decode(db.get(blockhash), Block, db=db)
  File "/usr/local/lib/python2.7/dist-packages/rlp-0.3.3-py2.7.egg/rlp/codec.py", line 164, in decode
    return sedes.deserialize(item, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rlp-0.3.3-py2.7.egg/rlp/sedes/lists.py", line 145, in deserialize
    values = cls.get_sedes().deserialize(serial)
  File "/usr/local/lib/python2.7/dist-packages/rlp-0.3.3-py2.7.egg/rlp/sedes/lists.py", line 54, in deserialize
    for element, sedes in izip(serial, self)]
  File "/usr/local/lib/python2.7/dist-packages/rlp-0.3.3-py2.7.egg/rlp/sedes/lists.py", line 145, in deserialize
    values = cls.get_sedes().deserialize(serial)
  File "/usr/local/lib/python2.7/dist-packages/rlp-0.3.3-py2.7.egg/rlp/sedes/lists.py", line 52, in deserialize
    raise DeserializationError('List has wrong length', serial)
rlp.exceptions.DeserializationError: List has wrong length

**Comment by konradkonrad** [comment]
@vibhor1403 is this still an issue?
