### ISSUE TITLE
abi.py doesn't like Solidity constructors

### ISSUE THREAD

**Issue by robmyers** [ethereum/pyethereum#260]
Example code:

```
from ethereum import tester,

solidity_contract = """
contract zoo {
    function sub2() returns (int256 y) {
        y = 7;
    }
    function zoo() {}
}
"""

s = tester.state()
contract = s.abi_contract(solidity_contract, language='solidity')
```

For reference, the abi is:

```
[{'inputs': [], 'constant': False, 'type': 'function', 'name': 'sub2', 'outputs': [{'type': 'int256', 'name': 'y'}]}, {'inputs': [], 'type': 'constructor'}]
```

Ouput from running:

```
 $ python test.py 
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    contract = s.abi_contract(solidity_contract, language='solidity')
  File "/usr/local/lib/python2.7/dist-packages/ethereum-0.9.66-py2.7.egg/ethereum/tester.py", line 158, in abi_contract
    return ABIContract(self, _abi, address, listen=listen, log_listener=log_listener)
  File "/usr/local/lib/python2.7/dist-packages/ethereum-0.9.66-py2.7.egg/ethereum/tester.py", line 71, in __init__
    self._translator = abi.ContractTranslator(_abi)
  File "/usr/local/lib/python2.7/dist-packages/ethereum-0.9.66-py2.7.egg/ethereum/abi.py", line 25, in __init__
    name = sig_item['name']
KeyError: 'name'
```

**Comment by jorisbontje** [comment]
+1

**Comment by jorisbontje** [comment]
@ryepdx do you have any update on this?

**Comment by ryepdx** [comment]
It didn't look like my code was implicated in the failing Travis CI check.

**Comment by RomanZacharia** [comment]
@robmyers , @jorisbontje , @ryepdx Seems like the issue is resolved. Can you confirm?
