### ISSUE TITLE
pyethereum failing on stateTest

### ISSUE THREAD

**Issue by winsvega** [ethereum/pyethereum#269]
Test:
https://github.com/ethereum/tests/commit/e0b800e3981e3f436a6bcdd9cb3266778b54221c

Output:
"
Traceback (most recent call last):
  File "/home/wins/Ethereum/pyethereum/ethereum/tests/test_state.py", line 40, in <module>
    testutils.check_state_test(testdata)
  File "/home/wins/Ethereum/pyethereum/ethereum/testutils.py", line 35, in <lambda>
    check_state_test = lambda params: run_state_test(params, VERIFY)
  File "/home/wins/Ethereum/pyethereum/ethereum/testutils.py", line 368, in run_state_test
    compare_post_states(shouldbe, reallyis)
  File "/home/wins/Ethereum/pyethereum/ethereum/testutils.py", line 82, in compare_post_states
    (k, s, r))
Exception: Key u'000000000000000000000000000000001cd49878'

shouldbe: {'nonce': 0, 'balance': 711702023, 'storage': {}, 'code': '0x'} 

reallyis: {'nonce': 0, 'balance': 0, 'storage': {}, 'code': '0x'}
Testing: stdin randomStatetest2 0 105
"

**Comment by RomanZacharia** [comment]
The pyethereum currently passes all the tests
https://travis-ci.org/ethereum/pyethereum/builds/115013213
@winsvega can this issue be closed?
