### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by winsun** [ethereum/pyethereum#339]
assert sha3('').encode('hex') == 'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'
AssertionError

in mac osx 10.9, when i run test_contacts.py, which give a error

**Comment by RomanZacharia** [comment]
@winsun can't reproduce your issue, could you please provide more details?

**Comment by lbrth** [comment]
I've the same problem, it's when I want to import pyethereum. Somebody know how to solve it ?

**Comment by jzandbergen** [comment]
Yep, same problem here as well. 
If i open up a python shell and just enter "import ethereum" I get the same error.

Python version: 2.7.12
pyethereum version: 1.6.0

Let me know if I can provide any other useful information.

**Comment by mikeshultz** [comment]
Since nobody else is offering up more detail, I'll add what I saw.

    $ python test_contracts.py 
    Traceback (most recent call last):
      File "test_contracts.py", line 9, in <module>
        from ethereum import tester, utils, abi
      File "/home/mike/.venvs/pyethereum/lib/python3.5/site-packages/ethereum-1.6.1-py3.5.egg/ethereum/__init__.py", line 8, in <module>
        from . import slogging  # noqa
      File "/home/mike/.venvs/pyethereum/lib/python3.5/site-packages/ethereum-1.6.1-py3.5.egg/ethereum/slogging.py", line 6, in <module>
        from ethereum.utils import bcolors, is_numeric
      File "/home/mike/.venvs/pyethereum/lib/python3.5/site-packages/ethereum-1.6.1-py3.5.egg/ethereum/utils.py", line 187, in <module>
        assert encode_hex(sha3(b'')) == 'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'
    AssertionError

.

    $ cat /etc/*release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
    NAME="Ubuntu"
    VERSION="16.04.2 LTS (Xenial Xerus)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 16.04.2 LTS"
    VERSION_ID="16.04"
    HOME_URL="http://www.ubuntu.com/"
    SUPPORT_URL="http://help.ubuntu.com/"
    BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
    VERSION_CODENAME=xenial
    UBUNTU_CODENAME=xenial

.

    $ python --version
    Python 3.5.2

.

    $ pip freeze
    bitcoin==1.1.42
    cffi==1.10.0
    coverage==4.4.1
    coveralls==1.1
    docopt==0.6.2
    ethereum==1.6.1
    ethereum-serpent==2.0.2
    pbkdf2==1.3
    pkg-resources==0.0.0
    pluggy==0.4.0
    py==1.4.33
    pycparser==2.17
    pycryptodome==3.4.5
    pyethash==0.1.23
    pysha3==1.0.2
    pytest==3.0.7
    pytest-catchlog==1.2.2
    pytest-timeout==1.0.0
    PyYAML==3.12
    repoze.lru==0.6
    requests==2.14.2
    rlp==0.5.1
    scrypt==0.8.0
    secp256k1==0.13.2
    tox==2.7.0
    virtualenv==15.1.0

Let me know if there's any more detail I can add.  I'll keep digging on my end.
