### ISSUE TITLE
Errors on installation

### ISSUE THREAD

**Issue by priestc** [ethereum/pyethereum#356]
~/pyethereum (develop)$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to ethereum.egg-info/requires.txt
writing ethereum.egg-info/PKG-INFO
writing top-level names to ethereum.egg-info/top_level.txt
writing dependency_links to ethereum.egg-info/dependency_links.txt
reading manifest file 'ethereum.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ethereum.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/ethereum
copying ethereum/abi.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/spv.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/config.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/__init__.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/compress.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/transactions.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/opcodes.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/db.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/_solidity.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/specials.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/bloom.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/processblock.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/ethash_utils.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/fast_rlp.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/fastvm.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/chain.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/securetrie.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/tester.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/exceptions.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/ethpow.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/trie.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/vm.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/slogging.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/testutils.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/blocks.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/refcount_db.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/keys.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/ethash.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/pruning_trie.py -> build/lib.linux-x86_64-2.7/ethereum
copying ethereum/utils.py -> build/lib.linux-x86_64-2.7/ethereum
creating build/lib.linux-x86_64-2.7/tools
copying tools/__init__.py -> build/lib.linux-x86_64-2.7/tools
copying tools/random_vm_test_generator.py -> build/lib.linux-x86_64-2.7/tools
copying tools/keystorer.py -> build/lib.linux-x86_64-2.7/tools
copying tools/fixture_to_example.py -> build/lib.linux-x86_64-2.7/tools
copying tools/vm_test_generator.py -> build/lib.linux-x86_64-2.7/tools
creating build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/__init__.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_trie_next_prev.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_blockhashes.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/profile_vm.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_chain.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/conftest.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/bintrie.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_pruning_trie.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_difficulty.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_blocks.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_trie.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_abi.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/stress_test.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/benchmark_db.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_vm.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_bloom.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_remoteblocks.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_transactions.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_keys.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_compress.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_vm_failing.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_logging.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_state.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_contracts.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_db.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_serialization.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_genesis.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/utils.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_solidity.py -> build/lib.linux-x86_64-2.7/ethereum/tests
copying ethereum/tests/test_ethash.py -> build/lib.linux-x86_64-2.7/ethereum/tests
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/abi.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/spv.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/config.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/__init__.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/compress.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/transactions.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/opcodes.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/db.py -> build/bdist.linux-x86_64/egg/ethereum
creating build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/__init__.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_trie_next_prev.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_blockhashes.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/profile_vm.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_chain.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/conftest.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/bintrie.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_pruning_trie.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_difficulty.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_blocks.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_trie.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_abi.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/stress_test.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/benchmark_db.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_vm.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_bloom.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_remoteblocks.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_transactions.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_keys.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_compress.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_vm_failing.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_logging.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_state.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_contracts.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_db.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_serialization.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_genesis.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/utils.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_solidity.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/tests/test_ethash.py -> build/bdist.linux-x86_64/egg/ethereum/tests
copying build/lib.linux-x86_64-2.7/ethereum/_solidity.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/specials.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/bloom.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/processblock.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/ethash_utils.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/fast_rlp.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/fastvm.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/chain.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/securetrie.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/tester.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/exceptions.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/ethpow.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/trie.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/vm.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/slogging.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/testutils.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/blocks.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/refcount_db.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/keys.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/ethash.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/pruning_trie.py -> build/bdist.linux-x86_64/egg/ethereum
copying build/lib.linux-x86_64-2.7/ethereum/utils.py -> build/bdist.linux-x86_64/egg/ethereum
creating build/bdist.linux-x86_64/egg/tools
copying build/lib.linux-x86_64-2.7/tools/__init__.py -> build/bdist.linux-x86_64/egg/tools
copying build/lib.linux-x86_64-2.7/tools/random_vm_test_generator.py -> build/bdist.linux-x86_64/egg/tools
copying build/lib.linux-x86_64-2.7/tools/keystorer.py -> build/bdist.linux-x86_64/egg/tools
copying build/lib.linux-x86_64-2.7/tools/fixture_to_example.py -> build/bdist.linux-x86_64/egg/tools
copying build/lib.linux-x86_64-2.7/tools/vm_test_generator.py -> build/bdist.linux-x86_64/egg/tools
byte-compiling build/bdist.linux-x86_64/egg/ethereum/abi.py to abi.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/spv.py to spv.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/config.py to config.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/compress.py to compress.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/transactions.py to transactions.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/opcodes.py to opcodes.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/db.py to db.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_trie_next_prev.py to test_trie_next_prev.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_blockhashes.py to test_blockhashes.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/profile_vm.py to profile_vm.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_chain.py to test_chain.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/conftest.py to conftest.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/bintrie.py to bintrie.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_pruning_trie.py to test_pruning_trie.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_difficulty.py to test_difficulty.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_blocks.py to test_blocks.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_trie.py to test_trie.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_abi.py to test_abi.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/stress_test.py to stress_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/benchmark_db.py to benchmark_db.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_vm.py to test_vm.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_bloom.py to test_bloom.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_remoteblocks.py to test_remoteblocks.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_transactions.py to test_transactions.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_keys.py to test_keys.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_compress.py to test_compress.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_vm_failing.py to test_vm_failing.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_logging.py to test_logging.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_state.py to test_state.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_contracts.py to test_contracts.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_db.py to test_db.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_serialization.py to test_serialization.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_genesis.py to test_genesis.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_solidity.py to test_solidity.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tests/test_ethash.py to test_ethash.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/_solidity.py to _solidity.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/specials.py to specials.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/bloom.py to bloom.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/processblock.py to processblock.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/ethash_utils.py to ethash_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/fast_rlp.py to fast_rlp.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/fastvm.py to fastvm.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/chain.py to chain.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/securetrie.py to securetrie.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/tester.py to tester.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/exceptions.py to exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/ethpow.py to ethpow.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/trie.py to trie.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/vm.py to vm.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/slogging.py to slogging.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/testutils.py to testutils.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/blocks.py to blocks.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/refcount_db.py to refcount_db.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/keys.py to keys.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/ethash.py to ethash.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/pruning_trie.py to pruning_trie.pyc
byte-compiling build/bdist.linux-x86_64/egg/ethereum/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/tools/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/tools/random_vm_test_generator.py to random_vm_test_generator.pyc
byte-compiling build/bdist.linux-x86_64/egg/tools/keystorer.py to keystorer.pyc
byte-compiling build/bdist.linux-x86_64/egg/tools/fixture_to_example.py to fixture_to_example.pyc
byte-compiling build/bdist.linux-x86_64/egg/tools/vm_test_generator.py to vm_test_generator.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ethereum.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ethereum.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ethereum.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ethereum.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ethereum.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
ethereum.testutils: module references __file__
ethereum.__init__: module references __file__
ethereum.tests.test_solidity: module references __file__
ethereum.tests.test_trie: module references __file__
creating dist
creating 'dist/ethereum-1.3.6-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ethereum-1.3.6-py2.7.egg
creating /home/chris/.virtualenvs/multiexplorer/lib/python2.7/site-packages/ethereum-1.3.6-py2.7.egg
Extracting ethereum-1.3.6-py2.7.egg to /home/chris/.virtualenvs/multiexplorer/lib/python2.7/site-packages
Removing ethereum 1.3.6 from easy-install.pth file
Adding ethereum 1.3.6 to easy-install.pth file

Installed /home/chris/.virtualenvs/multiexplorer/lib/python2.7/site-packages/ethereum-1.3.6-py2.7.egg
Processing dependencies for ethereum==1.3.6
Searching for secp256k1
Best match: secp256k1 0.11.1
Downloading https://github.com/ulope/secp256k1-py/archive/master.zip#egg=secp256k1-0.11.1
Processing master.zip
Writing /tmp/easy_install-ja2ShX/secp256k1-py-master/setup.cfg
Running secp256k1-py-master/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ja2ShX/secp256k1-py-master/egg-dist-tmp-jQN165
0.26

Installed /tmp/easy_install-ja2ShX/secp256k1-py-master/temp/easy_install-4_a6n_/pytest-runner-2.6.2/.eggs/setuptools_scm-1.11.1-py2.7.egg
zip_safe flag not set; analyzing archive contents...

Installed /tmp/easy_install-ja2ShX/secp256k1-py-master/.eggs/pytest_runner-2.6.2-py2.7.egg
Using bundled libsecp256k1
/tmp/easy_install-ja2ShX/secp256k1-py-master/libsecp256k1/autogen.sh: 3: /tmp/easy_install-ja2ShX/secp256k1-py-master/libsecp256k1/autogen.sh: autoreconf: not found
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    version=version,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 391, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 621, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 717, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 640, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 670, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 850, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1064, in run_setup
    run_setup(setup_script, args)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/chris/.virtualenvs/multiexplorer/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 140, in resume
    type, exc = map(pickle.loads, self._saved)
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
TypeError: __init__() takes at least 3 arguments (1 given)

**Comment by drandreaskrueger** [comment]
Same here


```
source ../venv/bin/activate
git clone https://github.com/ethereum/pyethereum/
cd pyethereum
sudo apt-get install libssl-dev libffi-dev
python setup.py install
```

```
  File "/home/andreas/myproject/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 140, in resume
    type, exc = map(pickle.loads, self._saved)
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
TypeError: __init__() takes at least 3 arguments (1 given)

```

Please help. Thanks.
