### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by suhalim9** [ethereum/pyethereum#400]
I cloned the git, installed dependencies, and ran the setup.py file but I am getting the following error when installing pyethereum. Can you please advise?

Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    'Programming Language :: Python :: 3.5',
  File "/System/Library/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/install.py", line 67, in run
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/install.py", line 117, in do_egg_install
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 391, in run
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 621, in easy_install
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 672, in install_item
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 717, in process_distribution
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/**init**.py", line 826, in resolve
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/**init**.py", line 1092, in best_match
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/**init**.py", line 1104, in obtain
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 640, in easy_install
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 670, in install_item
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 850, in install_eggs
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 1078, in build_and_install
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 1064, in run_setup
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/sandbox.py", line 246, in run_setup
  File "/System/Library/anaconda/lib/python2.7/contextlib.py", line 35, in **exit**
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/sandbox.py", line 195, in setup_context
  File "/System/Library/anaconda/lib/python2.7/contextlib.py", line 35, in **exit**
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/sandbox.py", line 166, in save_modules
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/sandbox.py", line 140, in resume
  File "/System/Library/anaconda/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/System/Library/anaconda/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/System/Library/anaconda/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
TypeError: **init**() takes at least 3 arguments (1 given)

**Comment by joeykrug** [comment]
Seems to be a nonissue on os x now, reopen if still occurring
