### ISSUE TITLE
Sorry to ask about how to use ecsign. Thanks.

### ISSUE THREAD

**Issue by sunhuachuang** [ethereum/pyethereum#802]
```python
import hashlib
from ethereum.utils import ecsign

hash_value = hashlib.sha256(b'aaaa').hexdigest()
private_key = 'aaaa'

sig = ecsign(hash_value, private_key)
print(sig)
```
Error:
Traceback (most recent call last):
  File "test_buy.py", line 31, in <module>
    sig = ecsign(hash_value, private_key)
  File "/usr/lib/python3.6/site-packages/ethereum-2.0.4-py3.6.egg/ethereum/utils.py", line 122, in ecsign
    v, r, s = ecdsa_raw_sign(rawhash, key)
  File "/usr/lib/python3.6/site-packages/py_ecc-1.1.3-py3.6.egg/py_ecc/secp256k1/secp256k1.py", line 111, in ecdsa_raw_sign
  File "/usr/lib/python3.6/site-packages/py_ecc-1.1.3-py3.6.egg/py_ecc/secp256k1/secp256k1.py", line 21, in bytes_to_int
TypeError: unsupported operand type(s) for +: 'int' and 'str'

If use `hash_value.encode()`, It will Error: `TypeError: can't concat str to bytes`.
?

**Comment by hwwhww** [comment]
It looks like a Python3 compatible problem.
If you use Python2.7, your code works.

```
➜ python
Python 2.7.13 (default, Aug  7 2017, 14:34:09)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> from ethereum.utils import ecsign
>>>
>>> hash_value = hashlib.sha256(b'aaaa').hexdigest()
>>> private_key = 'aaaa'
>>> sig = ecsign(hash_value, private_key)
>>> print(sig)
(27L, 59350363646956340164423271639579597498902635753106918965031949852871162922966L, 55942339344401704830125773082009091916939852617911594847424091549117003519428L)
```

As for python3.6+, you may have to encode both `private_key` and `hash_value`.

```
➜ python
Python 3.6.1 (default, Jul 18 2017, 02:56:07)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> from ethereum.utils import ecsign
>>>
>>> hash_value = hashlib.sha256(b'aaaa').hexdigest().encode()
>>> private_key = 'aaaa'.encode()
>>>
>>> sig = ecsign(hash_value, private_key)
>>> print(sig)
(27, 59350363646956340164423271639579597498902635753106918965031949852871162922966, 55942339344401704830125773082009091916939852617911594847424091549117003519428)

```

**Comment by changwu-tw** [comment]
On py3, you need to encode str to bytes. 

```
import hashlib
from ethereum.utils import ecsign

hash_value = hashlib.sha256(b'aaaa').hexdigest()
private_key = 'aaaa'

sig = ecsign(hash_value.encode(), private_key.encode())
print(sig)
```

**Comment by sunhuachuang** [comment]
cool, Thank you @hwwhww
