### ISSUE TITLE
Maverick OSX Installation Problems - Coincurve-6.0.0 

### ISSUE THREAD

**Issue by pinnaclesystemsgroup** [ethereum/pyethereum#829]
Here is the last terminal messages tom the running of the 

running install
running bdist_egg
running egg_info
writing requirements to ethereum.egg-info/requires.txt
writing ethereum.egg-info/PKG-INFO
writing top-level names to ethereum.egg-info/top_level.txt
writing dependency_links to ethereum.egg-info/dependency_links.txt
reading manifest file 'ethereum.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ethereum.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/abi.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/block.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/bloom.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/child_dao_list.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/common.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/compress.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/config.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/consensus_strategy.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/db.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/exceptions.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
creating build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental
copying build/lib/ethereum/experimental/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental
copying build/lib/ethereum/experimental/fastvm.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental
copying build/lib/ethereum/experimental/pruning_trie.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental
copying build/lib/ethereum/experimental/refcount_db.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental
copying build/lib/ethereum/experimental/spv.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental
copying build/lib/ethereum/fast_rlp.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/fastvm.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/genesis_helpers.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
creating build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper
copying build/lib/ethereum/hybrid_casper/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper
copying build/lib/ethereum/hybrid_casper/casper_initiating_transactions.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper
copying build/lib/ethereum/hybrid_casper/casper_utils.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper
copying build/lib/ethereum/hybrid_casper/chain.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper
copying build/lib/ethereum/hybrid_casper/consensus.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper
copying build/lib/ethereum/hybrid_casper/validator.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper
copying build/lib/ethereum/messages.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/meta.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/new_state.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/opcodes.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
creating build/bdist.macosx-10.5-x86_64/egg/ethereum/pow
copying build/lib/ethereum/pow/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/pow
copying build/lib/ethereum/pow/chain.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/pow
copying build/lib/ethereum/pow/consensus.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/pow
copying build/lib/ethereum/pow/ethash.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/pow
copying build/lib/ethereum/pow/ethash_utils.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/pow
copying build/lib/ethereum/pow/ethpow.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/pow
copying build/lib/ethereum/securetrie.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/slogging.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/snapshot.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/specials.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/state.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
creating build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_abi.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_blocks.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_bloom.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_chain.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_compress.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_contracts.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_db.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_difficulty.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_genesis.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_keys.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_opcodes.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_serialization.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_state.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_tester.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_transactions.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_trie.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/test_trie_next_prev.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
copying build/lib/ethereum/tests/utils.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tests
creating build/bdist.macosx-10.5-x86_64/egg/ethereum/tools
copying build/lib/ethereum/tools/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tools
copying build/lib/ethereum/tools/_solidity.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tools
copying build/lib/ethereum/tools/keys.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tools
copying build/lib/ethereum/tools/new_statetest_utils.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tools
copying build/lib/ethereum/tools/tester.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tools
copying build/lib/ethereum/tools/testing_lang.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tools
copying build/lib/ethereum/tools/testutils.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum/tools
copying build/lib/ethereum/transaction_queue.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/transactions.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/trie.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/utils.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
copying build/lib/ethereum/vm.py -> build/bdist.macosx-10.5-x86_64/egg/ethereum
creating build/bdist.macosx-10.5-x86_64/egg/tools
copying build/lib/tools/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/tools
copying build/lib/tools/evm.py -> build/bdist.macosx-10.5-x86_64/egg/tools
copying build/lib/tools/fixture_to_example.py -> build/bdist.macosx-10.5-x86_64/egg/tools
copying build/lib/tools/keystorer.py -> build/bdist.macosx-10.5-x86_64/egg/tools
copying build/lib/tools/mk_ecadd_tests.py -> build/bdist.macosx-10.5-x86_64/egg/tools
copying build/lib/tools/mk_ecmul_tests.py -> build/bdist.macosx-10.5-x86_64/egg/tools
copying build/lib/tools/mk_ecpairing_tests.py -> build/bdist.macosx-10.5-x86_64/egg/tools
copying build/lib/tools/mk_modexp_tests.py -> build/bdist.macosx-10.5-x86_64/egg/tools
copying build/lib/tools/random_vm_test_generator.py -> build/bdist.macosx-10.5-x86_64/egg/tools
copying build/lib/tools/vm_test_generator.py -> build/bdist.macosx-10.5-x86_64/egg/tools
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/abi.py to abi.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/block.py to block.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/bloom.py to bloom.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/child_dao_list.py to child_dao_list.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/common.py to common.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/compress.py to compress.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/config.py to config.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/consensus_strategy.py to consensus_strategy.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/db.py to db.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/exceptions.py to exceptions.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental/fastvm.py to fastvm.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental/pruning_trie.py to pruning_trie.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental/refcount_db.py to refcount_db.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/experimental/spv.py to spv.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/fast_rlp.py to fast_rlp.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/fastvm.py to fastvm.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/genesis_helpers.py to genesis_helpers.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper/casper_initiating_transactions.py to casper_initiating_transactions.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper/casper_utils.py to casper_utils.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper/chain.py to chain.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper/consensus.py to consensus.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/hybrid_casper/validator.py to validator.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/messages.py to messages.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/meta.py to meta.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/new_state.py to new_state.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/opcodes.py to opcodes.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/pow/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/pow/chain.py to chain.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/pow/consensus.py to consensus.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/pow/ethash.py to ethash.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/pow/ethash_utils.py to ethash_utils.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/pow/ethpow.py to ethpow.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/securetrie.py to securetrie.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/slogging.py to slogging.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/snapshot.py to snapshot.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/specials.py to specials.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/state.py to state.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_abi.py to test_abi.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_blocks.py to test_blocks.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_bloom.py to test_bloom.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_chain.py to test_chain.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_compress.py to test_compress.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_contracts.py to test_contracts.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_db.py to test_db.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_difficulty.py to test_difficulty.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_genesis.py to test_genesis.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_keys.py to test_keys.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_opcodes.py to test_opcodes.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_serialization.py to test_serialization.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_state.py to test_state.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_tester.py to test_tester.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_transactions.py to test_transactions.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_trie.py to test_trie.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/test_trie_next_prev.py to test_trie_next_prev.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tests/utils.py to utils.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tools/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tools/_solidity.py to _solidity.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tools/keys.py to keys.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tools/new_statetest_utils.py to new_statetest_utils.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tools/tester.py to tester.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tools/testing_lang.py to testing_lang.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/tools/testutils.py to testutils.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/transaction_queue.py to transaction_queue.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/transactions.py to transactions.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/trie.py to trie.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/utils.py to utils.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/ethereum/vm.py to vm.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/tools/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/tools/evm.py to evm.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/tools/fixture_to_example.py to fixture_to_example.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/tools/keystorer.py to keystorer.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/tools/mk_ecadd_tests.py to mk_ecadd_tests.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/tools/mk_ecmul_tests.py to mk_ecmul_tests.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/tools/mk_ecpairing_tests.py to mk_ecpairing_tests.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/tools/mk_modexp_tests.py to mk_modexp_tests.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/tools/random_vm_test_generator.py to random_vm_test_generator.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/tools/vm_test_generator.py to vm_test_generator.pyc
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying ethereum.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying ethereum.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying ethereum.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying ethereum.egg-info/requires.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying ethereum.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
ethereum.__init__: module references __file__
ethereum.hybrid_casper.casper_utils: module references __file__
ethereum.tests.test_tester: module references __file__
ethereum.tests.test_trie: module references __file__
ethereum.tools.new_statetest_utils: module references __file__
ethereum.tools.testutils: module references __file__
creating 'dist/ethereum-2.1.2-py2.7.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing ethereum-2.1.2-py2.7.egg
removing '/Users/princeriley/anaconda/lib/python2.7/site-packages/ethereum-2.1.2-py2.7.egg' (and everything under it)
creating /Users/princeriley/anaconda/lib/python2.7/site-packages/ethereum-2.1.2-py2.7.egg
Extracting ethereum-2.1.2-py2.7.egg to /Users/princeriley/anaconda/lib/python2.7/site-packages
ethereum 2.1.2 is already the active version in easy-install.pth

python setup.py install

Installed /Users/...../anaconda/lib/python2.7/site-packages/ethereum-2.1.2-py2.7.egg
Processing dependencies for ethereum==2.1.2
Searching for coincurve>=5.0.1
Reading https://pypi.python.org/simple/coincurve/
Downloading https://pypi.python.org/packages/1e/b8/d5dbe751304372debb356085717af0f1a274da37e7f51642e118a6497208/coincurve-6.0.0.tar.gz#md5=c8f1c2bf3879aa774424189c9d3df3e7
Best match: coincurve 6.0.0
Processing coincurve-6.0.0.tar.gz
Writing /tmp/easy_install-xXMVr0/coincurve-6.0.0/setup.cfg
Running coincurve-6.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xXMVr0/coincurve-6.0.0/egg-dist-tmp-0VozUS
zip_safe flag not set; analyzing archive contents...

We reach the following point during the installation .....

Installed /private/tmp/easy_install-xXMVr0/coincurve-6.0.0/.eggs/pytest_runner-3.0-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    'Programming Language :: Python :: 3.6',
  File "/Users/...../anaconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/...../anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/...../anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 745, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/...../anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
    replace_conflicting=replace_conflicting
  File "/Users/...../anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in best_match
    return self.obtain(req, installer)
  File "/Users/...../anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1153, in obtain
    return installer(requirement)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
    run_setup(setup_script, args)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/Users/...../anaconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/Users/...../anaconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 145, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-xXMVr0/coincurve-6.0.0/setup.py", line 313, in <module>
    
  File "/Users/...../anaconda/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/dist.py", line 338, in __init__
    _Distribution.__init__(self, attrs)
  File "/Users/...../anaconda/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/Users/...../anaconda/lib/python2.7/site-packages/setuptools/dist.py", line 471, in finalize_options
    ep.load()(self, ep.name, value)
  File "/Users/...../anaconda/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 161, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/Users/...../anaconda/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 48, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/Users/...../anaconda/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 24, in execfile
    exec(code, glob, glob)
  File "_cffi_build/build.py", line 32, in <module>
  File "_cffi_build/build.py", line 13, in _mk_ffi
  File "/Users/...../anaconda/lib/python2.7/site-packages/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 1.5.2 != 1.6.0

**Comment by JacobIRR** [comment]
The README.md contains an `apt-get` command for some packages - I'm curious how you did this on MacOS?

**Comment by ofek** [comment]
@pinnaclesystemsgroup https://github.com/pyca/cryptography/issues/2491#issuecomment-159379869 may help
