### ISSUE TITLE
No module name blocks and processblock.

### ISSUE THREAD

**Issue by cmaliwal** [ethereum/pyethereum#847]
```
>>> from ethereum import blocks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name blocks
>>> from ethereum import processblock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name processblock
```

**Comment by joeykrug** [comment]
-> `from ethereum import block`
