### ISSUE TITLE
rlp.utils don't has decode_hex

### ISSUE THREAD

**Issue by yihuang** [ethereum/pyethereum#868]
```
Traceback (most recent call last):
  File "erc20token/sdk.py", line 16, in <module>
    from ethereum.transactions import Transaction
  File ".../.env/lib/python3.5/site-packages/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File ".../.env/lib/python3.5/site-packages/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File ".../.env/lib/python3.5/site-packages/ethereum/utils.py", line 13, in <module>
    from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'
```

Wrong pyrlp version?

**Comment by SoYouDie** [comment]
Downgrade rlp lib version to 0.4.7 as temporary solution.

**Comment by Uxio0** [comment]
A quick fix:

`pip install rlp==0.6.0`
