### ISSUE TITLE
for help

### ISSUE THREAD

**Issue by maiganne** [ethereum/pyethereum#871]
https://github.com/ethereum/pyethereum/blob/c8b6205e1e0e3c1c6618d4ccc128914ba85c5a77/ethereum/transactions.py#L198

when i excute a python script like this:
```
from web3 import Web3, HTTPProvider
import rlp
from ethereum.transactions import Transaction




w3 = Web3(HTTPProvider('http://192.168.214.178:8545'))

tx = Transaction(
    nonce=w3.eth.getTransactionCount(w3.eth.coinbase),
    gasprice=w3.eth.gasPrice,
    startgas=100000,
    to='0xd3cda913deb6f67967b99d67acdfa1712c293601',
    value=12345,
    data=b'',
)
```
i got a problem like this:
```
 Error
Traceback (most recent call last):
  File "/home/maiganne/projects/eth_project/venv/lib/python3.5/site-packages/twisted/trial/runner.py", line 781, in loadByName
    return self.suiteFactory([self.findByName(name, recurse=recurse)])
  File "/home/maiganne/projects/eth_project/venv/lib/python3.5/site-packages/twisted/trial/runner.py", line 679, in findByName
    __import__(name)
  File "/home/maiganne/projects/eth_project/test_contract.py", line 10, in <module>
    from ethereum.transactions import Transaction
  File "/home/maiganne/projects/eth_project/venv/lib/python3.5/site-packages/ethereum/transactions.py", line 198, in <module>
    UnsignedTransaction = Transaction.exclude(['v', 'r', 's'])
AttributeError: type object 'Transaction' has no attribute 'exclude'
```
why? does the object Transction has the method exclude?

**Comment by leonardol** [comment]
Hi,
I'm pretty sure that the issue you mentioned above is related to the new version of pyrlp (see: https://github.com/ethereum/pyrlp/issues/61). There is no more the `exclude` method so it should be necessary to update the Transaction class, to solve the problem.

**Comment by EgorXor** [comment]
same problem

**Comment by jo-tud** [comment]
same here

**Comment by sontranrad** [comment]
hello,
Is there any way to get this solved ? I'm getting into the same situation. @leonardol , as many classes using Transaction class, if I extend it to fix the RLP stuffs, I will need to update many other classes as well. Is there any other solution ? Thanks

**Comment by adityasm96** [comment]
hello, has anyone found a solution to this problem!! 
Can someone please suggest if u have found one.
Thanks in advance
